language: go

go:
  - 1.2

before_install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/relops/csvb
  - go get github.com/cihub/seelog
  - export PATH=$PATH:/home/travis/gopath/bin:/usr/local/cassandra/bin

install: 
  - go get -v ./...

script:
  - make test

services:
  - cassandra